pull_request_rules:
  - name: thank user and refer them to add themself as contributor
    conditions:
      - merged
    actions:
      comment:
        message: "Thank you for your contribution, if you haven't already then feel free to add yourself as a contributors through the all-contributors bot. See https://allcontributors.org/docs/en/bot/usage for more information."
